### ISSUE TITLE
Missing MetaGeek.Diagnostics and lib directory

### ISSUE THREAD

**Issue by brunofvalli** [metageek-llc/ManagedWifi#2]
On the ManagedWifi.csproj there is a reference to 

```
<Reference Include="MetaGeek.Diagnostics">
    <HintPath>..\lib\MetaGeek.Diagnostics.dll</HintPath>
</Reference>
```

Where can I find this dll?

**Comment by junkshow** [comment]
The dll can be found in the lib directory of the InSSIDer2 project.
https://github.com/metageek-llc/inSSIDer-2/tree/master/lib

**Comment by brunofvalli** [comment]
Thank you
